# Docker Compose for single sidetree bitcoin node

version: '3.4'
services:
  bitcore-sidetree:
    image: bitcore-sidetree:latest
    build: .
    ports:
      - 3001:3001
      - 3002:3002
    volumes:
      - bitcoin-data:/app/bitcore-sidetree/data

volumes:
  bitcoin-data:
